### ISSUE TITLE
Fix warnings from json files in target

### ISSUE THREAD

**Issue by stunjiturner** [nerdsupremacist/Graphaello#8] opened 2020-03-27 18:11 UTC
while working on creating a sample application, using the apollographl tutorial endpoint, https://apollo-fullstack-tutorial.herokuapp.com/

I am getting errors and warnings.

Showing Recent Issues
no rule to process file '/Users/stunjiturner/Downloads/CodeReviewRepos/OutOfThisWorld-Graphaello/ApolloFullstackTutorialHerokuappCom.graphql.json' of type 'text.json' for architecture 'x86_64'

Showing Recent Issues
/Users/stunjiturner/Downloads/CodeReviewRepos/OutOfThisWorld-Graphaello/Graphaello.swift:564:23: 'ApolloFullstackTutorialHerokuappCom' is ambiguous for type lookup in this context

**Comment by nerdsupremacist** [comment] 2020-03-30 01:47
This is a bug referring to how the json file is being added to the target

**Comment by nerdsupremacist** [comment] 2020-03-30 01:50
The issue is in this line: https://github.com/nerdsupremacist/Graphaello/blob/9c74459d8a2314f42d6198eb48e2c6829cb9b9a5/Sources/Graphaello/Processing/Project/Project.swift#L78

It it adding the json file as if it were a swift file.
We will need to check what it should be added as instead, and add an option to createFile to define the option

**Comment by nerdsupremacist** [comment] 2020-08-03 10:08
Oh forgot to write here that this issue was fixed with: 0.1.0-alpha.11

**Closed** 2020-08-03 10:08 UTC
Labels: Command Line, bug, good first issue
